(define (problem strips-blocks-soc)
    (:domain BLOCKS)
    (:objects A B)
    (:init (ONTABLE A) 
           (ON B A) 
           (CLEAR B) 
           (HANDEMPTY))
    (:goal (AND (ONTABLE A) 
                (ONTABLE B))))