(define (problem strips-blocks-soc)
    (:domain BLOCKS)
    (:objects A B)
    (:init (ONTABLE A) 
           (ON B A) 
           (CLEAR B) 
           (HANDEMPTY))
    (:goal (AND (ONTABLE B) 
                (ON A B) 
                (CLEAR A))))