image: ubuntu:18.04
pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -y upgrade

          # Install dependencies of this script.
          - apt-get -y install python2.7 python2.7-dev python3.6 python3.7 python-tox software-properties-common
          - add-apt-repository -y --update ppa:deadsnakes/ppa
          - apt-get -y install python3.5

          - tox
